#!/usr/bin/bash

read -p "Enter Opration(backup/restore/delete): " op

case $op in 
 backup)
  echo "going to take backup."
;;

restore)
  echo "going to restore the backup."
;;

delete)
  echo "going to delete a back up"
;;

*)
  echo "operation is not defined"
esac
