#!/usr/bin/bash

echo "Select the operation: "

select op in backup restore delete "exit"; do

 case $op in 
 backup)
  echo "going to take backup."
;;

restore)
  echo "going to restore the backup."
;;

delete)
  echo "going to delete a back up"
;;

"exit")
  exit 0
 esac
 
done
